dynamicPathPlanner:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  world_base_position_controller:
    type: effort_controllers/JointPositionController
    joint: world_base
    pid: {p: 1.0, i: 1.0, d: 0.0}