dynamicPathPlanner:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 20

  world_base_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: world_base_1
    pid: {p: 1.0, i: 1.0, d: 0.0}

  world_base_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: world_base_2
    pid: {p: 1.0, i: 1.0, d: 0.0}
